### ISSUE TITLE
Showing unavailable moves [PBI Example]

### ISSUE THREAD

**Issue by sjiang1** [COSC481W-2023Fall/git-practice-sjiang1#6]
**User Story** 
As a new player who just started learning to play our game, I would like to know all the unavailable moves (due to a lack of resources) and what resources I need to enable these moves _so that_ I can have a better plan to gain more achievements in the game in the long run.

- **Persona:** A new player who just started learning to play our game
- **Feature:** Showing all the unavailable moves (due to a lack of resources) and what resources are needed for these moves
- **Business Value:** New players can better plan for future moves to gain more achievements

**Reference to the Beta Testing**
Beta testing report: https://docs.google.com/document/d/1vhoOs4NjpspSQWeGlHkCMb4-3iUGDkHmRKshiRkHTUE/edit?usp=sharing
Item 3:

> They rolled the dice and tried to figure out what to do next.
> Q. How do I know what resources I need to make a move? A. Moves don’t currently appear unless you have enough resources. 
> Observations and reflections: Moves don’t appear unless you have enough resources, but it might be nice to have a modal with the game rules on screen. 
> Observations and reflections: The rule of "roads must be connected to a settlement or other road" is unclear to the user. We need to clarify this rule in the warning message.

**Tasks**

- [ ] Create a backend API to provide all the unavailable moves
- [ ] On the backend, calculate what resources are needed for the moves
- [ ] On the frontend, add a section to list all the unavailable moves
- [ ] On the frontend, for each unavailable move, have a pop-up view to list all the resources needed

**Acceptance Criteria**

1. When a player rolls the dice, the game should show all the unavailable moves (in addition to the available moves)
2. For each unavailable move, the game should show the resources that the player needs to enable the move
